### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by abanerjee123** [wesbarnett/libgmxcpp#3]
[  4%] Building CXX object src/CMakeFiles/gmxcpp.dir/Topology.cpp.o
/home/abanerjee/md/regromacsinputfile/libgmxcpp-master/src/Topology.cpp: In member function ‘void Topology::read(std::__cxx11::string)’:
/home/abanerjee/md/regromacsinputfile/libgmxcpp-master/src/Topology.cpp:58:62: error: cannot convert ‘gmx_mtop_t*’ to ‘float (*)[3]’ for argument ‘7’ to ‘int read_tpx(const char*, t_inputrec*, float (*)[3], int*, float (*)[3], float (*)[3], float (*)[3], gmx_mtop_t*)’
     read_tpx(tprfile.c_str(),NULL,NULL,&natoms,NULL,NULL,mtop);
                                                              ^
src/CMakeFiles/gmxcpp.dir/build.make:254: recipe for target 'src/CMakeFiles/gmxcpp.dir/Topology.cpp.o' failed
make[2]: *** [src/CMakeFiles/gmxcpp.dir/Topology.cpp.o] Error 1
CMakeFiles/Makefile2:103: recipe for target 'src/CMakeFiles/gmxcpp.dir/all' failed
make[1]: *** [src/CMakeFiles/gmxcpp.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by wesbarnett** [comment]
What version of GROMACS do you have installed?

**Comment by wesbarnett** [comment]
No response; closing.
