### ISSUE TITLE
compiling topology

### ISSUE THREAD

**Issue by doesm** [wesbarnett/libgmxcpp#5]
Hello, I'm getting an error compiling the library. I have gromacs 2018.1
...
[ 40%] Building CXX object src/CMakeFiles/gmxcpp.dir/Topology.cpp.o
/home/marcelo/Documents/libgmxcpp-5.0.2/src/Topology.cpp: In member function ‘void Topology::read(std::__cxx11::string)’:
/home/marcelo/Documents/libgmxcpp-5.0.2/src/Topology.cpp:58:51: error: too few arguments to function ‘t_topology gmx_mtop_t_to_t_topology(gmx_mtop_t*, bool)’
     t_topology top = gmx_mtop_t_to_t_topology(mtop);
                                                   ^
In file included from /home/marcelo/Documents/libgmxcpp-5.0.2/include/gmxcpp/Topology.h:38:0,
                 from /home/marcelo/Documents/libgmxcpp-5.0.2/src/Topology.cpp:31:
/usr/local/gromacs/include/gromacs/topology/mtop_util.h:221:1: note: declared here
 gmx_mtop_t_to_t_topology(gmx_mtop_t *mtop, bool freeMTop);
 ^~~~~~~~~~~~~~~~~~~~~~~~
src/CMakeFiles/gmxcpp.dir/build.make:254: recipe for target 'src/CMakeFiles/gmxcpp.dir/Topology.cpp.o' failed
make[2]: *** [src/CMakeFiles/gmxcpp.dir/Topology.cpp.o] Error 1
CMakeFiles/Makefile2:103: recipe for target 'src/CMakeFiles/gmxcpp.dir/all' failed
make[1]: *** [src/CMakeFiles/gmxcpp.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by wesbarnett** [comment]
I'm sorry to say that libgmxcpp must not be compatible with Gromacs 2018+. That version of Gromacs was released after the last release of libgmxcpp. Unfortunately I'm no longer an active Gromacs user. Hopefully someone can fork the repo if there is still interest in the community to make this work for future versions.
